debug:
  datatype: mysql
  hostname: bj-cynosdbmysql-grp-4febov7e.sql.tencentcdb.com
  database: sjds-test
  username: suntao
  password: SunTao123

test:
  datatype: mysql
  hostname: bj-cynosdbmysql-grp-4febov7e.sql.tencentcdb.com
  database: sjds-test
  username: suntao
  password: SunTao123

release:
  datatype: mysql
  hostname: localhost-rrr
  database: test
  username: root
  password: a1937258