debug:
  datatype: mysql
  hostname: 49.232.172.176
  database: keep
  username: root
  password: keep123

test:
  datatype: mysql
  hostname: 49.232.172.176
  database: keep
  username: root
  password: keep123

release:
  datatype: mysql
  hostname: 49.232.172.176
  database: keep
  username: root
  password: keep123