debug:
  datatype: mysql
  hostname: 112.126.61.95
  database: keep_happy
  username: keep
  password: openai

test:
  datatype: mysql
  hostname: 112.126.61.95
  database: keep_happy
  username: keep
  password: openai

release:
  datatype: mysql
  hostname: 112.126.61.95
  database: keep_happy
  username: keep
  password: openai